### ISSUE TITLE
点击概览显示空白

### ISSUE THREAD

**Issue by wiwide-ops** [0xbug/Hawkeye#23] opened 2017-10-18 09:30 UTC
点击概览下拉空白，
![image](https://user-images.githubusercontent.com/32890577/31711234-15472534-b42a-11e7-98db-e6c6d22f9726.png)

**Comment by wiwide-ops** [comment] 2017-10-18 09:45
Traceback (most recent call last):
  File "spider.py", line 211, in <module>
    crawl(query)
  File "spider.py", line 75, in crawl
    for page in range(int(sys.argv[1]), int(sys.argv[2])):
IndexError: list index out of range

**Comment by 0xbug** [comment] 2017-10-18 09:46
Duplicate of #20

**Comment by wiwide-ops** [comment] 2017-10-18 09:59
厉害了 好神速。 概览那里呢？

**Comment by 0xbug** [comment] 2017-10-18 10:00
显示抓取到的结果了吗，概览需要刷新才能更新

**Comment by wiwide-ops** [comment] 2017-10-18 10:01
赞赞赞！

**Closed** 2017-10-18 10:02 UTC
